config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :chairs, only: [ :index, :show, :new, :create ] do
    resources :bookings, only: [:new, :create ]
  end
  resources :bookings, only: [ :index, :show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :chair

  validates :start_date, :end_date, presence: true
  validates :status, inclusion: { in: %w[pending confirmed completed] }
  validate :end_date_after_start_date

  def end_date_after_start_date
    errors.add(:end_date, "must be after the start date") if end_date <= start_date
  end
end

app/models/chair.rb
class Chair < ApplicationRecord
  belongs_to :user
  has_many_attached :photos

  validates :name, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :chairs
  has_many :bookings

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 20 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # before_action :set_booking, only: %i[show edit update destroy]
  before_action :set_booking, only: %i[show]
  before_action :set_chair, only: %i[new create]

  def index
    @bookings = Booking.all
    @chairs = Chair.all
  end

  def new
    @booking = Booking.new
    @chair = Chair.find(params[:chair_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.chair = @chair

    if @booking.save
      redirect_to bookings_path, notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  # def edit
  # end

  # def update
  #   if @booking.update(booking_params)
  #     redirect_to @booking, notice: 'Booking was successfully updated.'
  #   else
  #     render :edit
  #   end
  # end

  # def destroy
  #   @booking.destroy
  #   redirect_to bookings_url, notice: 'Booking was successfully destroyed.'
  # end

  private

  def set_chair
    @chair = Chair.find(params[:chair_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:chair_id, :start_date, :end_date, :status)
  end
end

app/controllers/chairs_controller.rb
class ChairsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_chair, only: [:show]

  def index
    @chairs = Chair.all
  end

  def show
  end

  def new
    @chair = Chair.new
  end

  def create
    # @chair = Chair.new(chair_params)
    @chair = current_user.chairs.new(chair_params)
    if @chair.save
      redirect_to bookings_path, notice: 'Chair was successfully created.'
    else
      Rails.logger.debug @chair.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_chair
    @chair = Chair.find(params[:id])
  end

  def chair_params
    params.require(:chair).permit(:name, :price, :description, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">

  <div class="row justify-content-between" style="padding-left: 16px; padding-top: 16px;">

    <div class="categ col-6 py-2 mt-2" style="display: flex; flex-direction: column;">
      <h3>My Bookings</h3>

      <div class="cards-my-bookings py-2 mt-2" style="display: flex; flex-direction: column;">
        <% current_user.bookings.each do |booking| %>
          <div class="cards-my-bookings-infos" style="display:flex" >
            <% if booking.chair.photos.attached? %>
              <%= cl_image_tag(booking.chair.photos.first.key, alt: booking.chair.name, class: 'chair-image', style: 'max-width: 100px;') %>
            <% else %>
              <img style="max-width: 100px;" src="<%= booking.chair.image_url %>" alt="<%= booking.chair.name %>" />
            <% end %>
            <div class="card-details">
              <h4><%= booking.chair.name %></h4>
              <p><%= booking.start_date %> - <%= booking.end_date %> </p>
            </div>
          </div>
        <% end %>

      </div>
    </div>

    <div class="categ col-6 py-2 mt-2" style="display: flex; flex-direction: column;">
      <h3>My Chairs</h3>

      <div class="cards-my-chairs py-2 mt-2" style="display: flex; flex-direction: column;">
        <% current_user.chairs.each do |chair| %>
          <div class="cards-my-chairs-infos" style="display:flex">
            <% if chair.photos.attached? %>
              <%= cl_image_tag(chair.photos.first.key, alt: chair.name, class: 'chair-image', style: 'max-width: 100px;') %>
            <% else %>
              <img style="max-width: 100px;" src="<%= chair.image_url %>" alt="<%= chair.name %>" />
            <% end %>
            <div class="card-details">
              <h4> <%= chair.name %> </h4>
              <p> £<%= chair.price %> </p>
            </div>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container" style="margin-top: 10px;">
  <div class="row">
    <div class="col">
      <h1 class="text-center" style="padding-left: 16px; padding-top: 16px;">New booking</h1>
      <h2 class="text-center" style="padding-left: 16px; padding-top: 16px;"><%= @chair.name %> - £<%= @chair.price %>/day </h2>
    </div>
  </div>

  <div class="col-md-6 offset-md-3">
    <%= simple_form_for [@chair, @booking] do |f| %>
      <div class="form-row" style="display: flex;">
        <div class="form-group col-md-6">
          <%= f.input :start_date, html5: true, label: 'Start Date' %>
        </div>
        <div class="form-group col-md-6">
          <%= f.input :end_date, html5: true, label: 'End Date' %>
        </div>
      </div>
      <div class="form-group" style="justify-content: center; display: flex">
        <%= f.submit "Book", class:"book-now-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Booking details</h1>
    </div>
  </div>
</div>

app/views/chairs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1 style="padding-left: 16px; padding-top: 16px;">All Chairs</h1>
      <div class="cards">
        <% @chairs.each do |chair| %>
          <%= link_to chair_path(chair) do %>
            <div class="chair-card">
              <% if chair.photos.attached? %>
                <% chair.photos.each do |photo| %>
                  <%= cl_image_tag(photo.key, alt: chair.name, class: 'chair-image') %>
                <% end %>
              <% else %>
                <img src="<%= chair.image_url %>" alt="<%= chair.name %>" class="chair-image">
              <% end %>

              <div class="chair-info">
                <div class="chair-details">
                  <h5> <%= chair.name %> </h5>
                  <p> £<%= chair.price %> per day </p>
                </div>

                <%# <div class="view-button"> %>
                  <%#= link_to 'View chair', chair_path(chair) %>
                <%# </div> %>
              </div>
            </div>
          <% end %>
        <% end %>

      </div>
    </div>
  </div>
<div>

app/views/chairs/new.html.erb
<div class="container mt-4 d-flex justify-content-center align-items-center">
  <div class="row w-100">
    <div class="col-md-6 offset-md-3">
      <h1 class="text-center" style="padding-left: 16px; padding-top: 16px;">Rent out your chair</h1>
      <div>
        <%= simple_form_for (@chair) do |f| %>
          <%= f.input :name %>
          <%= f.input :price %>
          <%= f.input :description, as: :text, label: 'Description', input_html: { rows: 4, placeholder: 'Enter a brief description of the chair...' } %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <div class="form-group" style="justify-content: center; display: flex">
          <%= f.submit "Add chair", class:"book-now-btn" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/chairs/show.html.erb
<div class="chair-container">
  <div class="card-show">

    <div class="card-image">

      <% if @chair.photos.attached? %>
        <% @chair.photos.each do |photo| %>
          <%= cl_image_tag(photo.key, alt: @chair.name) %>
        <% end %>
      <% else %>
        <img src="<%= @chair.image_url %>" alt="<%= @chair.name %>">
      <% end %>
      <div class="image-info-link">
        <div class="back-btn-container">
          <%= link_to "Back to all chairs", chairs_path, class: "back-btn" %>
        </div>
      </div>
    </div>
    
    <div class="card-content">
    <div class="card-show-details">
      <h5><%= @chair.name %></h5>
      <p>£<%= @chair.price %> per day</p>
      <p>Sold by <%= @chair.user.username %></p>
      <h5> Description: </h5>
      <p> <%= @chair.description %> </p>
        <hr><hr>
        <%= link_to "Book Now", new_chair_booking_path(@chair), class: "book-now-btn" %>
      </div>

    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Chairbnb" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%# https://cdn.openart.ai/stable_diffusion/e92379b281a016a6a228db309444c4167cbe5633_2000x2000.webp %>
<%# https://img.freepik.com/premium-photo/game-thrones-throne-with-red-seat-iron-throne-it_902639-63145.jpg?w=2000 %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.openart.ai/stable_diffusion/e92379b281a016a6a228db309444c4167cbe5633_2000x2000.webp);">
  <div class="home-content">
    <div class="home-text">
      <h1><strong>Welcome to ChairBnB</strong></h1>
      <p>Seat Your Dreams: Buy, Sell, and Rent the World's Most Exclusive and Luxurious Chairs</p>
    </div>

    <div class="home-link">
      <%= link_to "See all chairs", chairs_path %>
    </div>
  </div>
</div>

<%# <p>"Find me in app/views/pages/home.html.erb"</p> %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "seated_chair.png" %>
        <%= image_tag "chairbnb_logo.png", style: "width:100px; height:50px" %>
      <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", chairs_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "user_avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "List a new chair", new_chair_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>